---
- name: Ensure libselinux-python is installed
  become: true
  ansible.builtin.dnf:
    name: libselinux-python3,policycoreutils-python3
    state: present

- name: Allow CGW to bind to port 8082
  become: true
  community.general.seport:
    ports: 8082
    proto: tcp
    setype: http_port_t

- name: Allow SRS to bind to port 8081
  become: true
  community.general.seport:
    ports: 8081
    proto: tcp
    setype: http_port_t
