---
# defaults file for ahu_services.censhare.sclient
censhare_sclient_repo_user: rpm_repo_user
censhare_sclient_repo_pass: rpm_repo_pass
censhare_sclient_censhare_version: "2023.1.2"
censhare_sclient_tools_version: latest
censhare_sclient_svc_user: service-client
censhare_sclient_svc_pass: secret
censhare_sclient_svc_host: censhare-hostname
censhare_sclient_collabora_version: latest
censhare_sclient_direct_volumes: false
censhare_sclient_volumes:
  - /assets:/assets/
censhare_sclient_volumes_info:
  assets:
    physicalurl: "file:///assets/"
    filestreaming: "false"
  assets-temp:
    physicalurl: "file:///assets/assets-temp/"
    filestreaming: "false"
  temp:
    physicalurl: "file:///assets/temp/"
    filestreaming: "false"
