---
- name: Converge
  hosts: loadbalancer
  remote_user: asudo
  vars:
    censhare_proxy_backends:
      - name: mockup
        address: nginx-backend
  tasks:
    - name: "Include ahu_services.censhare.censhare_proxy"
      ansible.builtin.include_role:
        name: "ahu_services.censhare.censhare_proxy"
