---
- name: Prepare
  hosts: loadbalancer
  remote_user: root
  gather_facts: true
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name: sudo
    - name: Create sudo user
      ansible.builtin.user:
        name: asudo
        group: wheel
    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Install firewalld and SELinux
      ansible.builtin.dnf:
        name: firewalld,selinux-policy,python3-libselinux
    - name: Ensure firewalld is configured to use iptables backend
      become: true
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: '^FirewallBackend='
        line: 'FirewallBackend=iptables'
    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
    - name: Set fact distirbution version 9 or later
      ansible.builtin.set_fact:
        distribution_later_9: ansible_distribution_major_version | int < 9
    - name: Enable SELinux
      ansible.posix.selinux:
        policy: "{{ distribution_later_9 | ternary('targeted', 'mls') }}"
        state: enforcing
