---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "censhare-${image:-al}-${tag:-9}"
    image: "${namespace:-mullholland}/${image:-docker-almalinux-systemd}:${tag:-9}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    override_command: false
    networks: 
      - name: dockernet    
    groups:
      - censhare
  - name: "psql14"
    image: "postgres:14-alpine"
    networks: 
      - name: dockernet
    pre_build_image: true
    override_command: false
    env:
      POSTGRES_USER: corpus
      POSTGRES_PASSWORD: corpus
provisioner:
  name: ansible
  playbooks:
    side_effect: selinux.yml  
  env:
    CENSHARE_REPO_USER: "${CENSHARE_REPO_USER}"
    CENSHARE_REPO_PASS: "${CENSHARE_REPO_PASS}"
verifier:
  name: ansible
