---
# defaults file for ahu_services.censhare.censhare_sclient
censhare_sclient_repo_user: rpm_repo_user
censhare_sclient_repo_pass: rpm_repo_pass
censhare_sclient_censhare_version: "2023.1.2"
censhare_sclient_tools_image: docker.io/ahuservices/cs-image-tools
censhare_sclient_tools_version: latest
censhare_sclient_svc_user: service-client
censhare_sclient_svc_pass: secret
censhare_sclient_svc_host: censhare-hostname
censhare_sclient_rmi_port: 30550
censhare_sclient_callback_host: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0] | default(inventory_hostname)) }}"
censhare_sclient_collabora_version: latest
censhare_sclient_collabora_image: docker.io/collabora/code
censhare_sclient_collabora_extra_params: "--o:ssl.enable=false"
censhare_sclient_container_network: censhare
censhare_sclient_direct_volumes: false
censhare_sclient_instances: 4
censhare_sclient_svc_appendix: ""
censhare_sclient_collabora_appendix: "{{ censhare_sclient_svc_appendix }}"
censhare_sclient_svc_name: "service-client{{ censhare_sclient_svc_appendix }}"
censhare_sclient_collabora_name: "collabora{{ censhare_sclient_collabora_appendix }}"
censhare_sclient_firewalld_service: "censhare-service-client{{ censhare_sclient_svc_appendix }}"
censhare_sclient_office_url: "http://{{ censhare_sclient_collabora_name }}:9980/cool/convert-to/pdf"
censhare_sclient_service_unit: "{{ censhare_sclient_svc_name }}.service"
censhare_sclient_collabora_service_unit: "{{ censhare_sclient_collabora_name }}.service"
censhare_sclient_iccprofiles_dir: /opt/iccprofiles
censhare_sclient_volumes:
  - /assets:/assets/
censhare_sclient_volumes_info:
  assets:
    physicalurl: "file:///assets/"
    filestreaming: "false"
  assets-temp:
    physicalurl: "file:///assets/assets-temp/"
    filestreaming: "false"
  temp:
    physicalurl: "file:///assets/temp/"
    filestreaming: "false"
