---
- name: Converge
  hosts: all
  remote_user: asudo
  vars:
    censhare_sclient_repo_user: "{{ lookup('ansible.builtin.env', 'CENSHARE_REPO_USER') }}"
    censhare_sclient_repo_pass: "{{ lookup('ansible.builtin.env', 'CENSHARE_REPO_PASS') }}"
  tasks:
    - name: "Include ahu_services.censhare.sclient"
      ansible.builtin.include_role:
        name: "ahu_services.censhare.sclient"
