---
# tasks file for installing Podman

- name: Install Podman
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Create Podman network for keycloak
  become: true
  containers.podman.podman_network:
    name: keycloak
    state: present
