---
- name: Converge
  hosts: censhare
  remote_user: asudo
  vars:
    censhare_server_db_host: "psql14"
    censhare_server_repo_user: "{{ lookup('ansible.builtin.env', 'CENSHARE_REPO_USER') }}"
    censhare_server_repo_pass: "{{ lookup('ansible.builtin.env', 'CENSHARE_REPO_PASS') }}"
    censhare_server_mail_enabled: true
  tasks:
    - name: "Include ahu_services.censhare.censhare_server"
      ansible.builtin.include_role:
        name: "ahu_services.censhare.censhare_server"
