---
- name: Restart collabora quadlet
  become: true
  ansible.builtin.systemd:
    name: "{{ censhare_sclient_collabora_service_unit }}"
    daemon_reload: true
    state: restarted
  tags:
    - css_update

- name: Restart service-client quadlet
  become: true
  ansible.builtin.systemd:
    name: "{{ censhare_sclient_service_unit }}"
    daemon_reload: true
    state: restarted
  tags:
    - css_update

- name: Reload firewalld
  become: true
  ansible.posix.firewalld:
    state: reloaded
