---
censhare_proxy_backends:
  - name: localhost
    address: localhost
censhare_proxy_backends_keycloak: "{{ censhare_proxy_backends }}"
censhare_proxy_backends_css: "{{ censhare_proxy_backends }}"
censhare_proxy_backends_rmi: "{{ censhare_proxy_backends }}"
censhare_proxy_backends_cgw: "{{ censhare_proxy_backends }}"
censhare_proxy_keycloak_port: 8080
censhare_proxy_cgw_port: 8082
censhare_proxy_css_port: 9000
censhare_proxy_rmi_port: 30546
censhare_proxy_timeout_client: "1m"
censhare_proxy_timeout_server: "1m"

# timeout configurations
censhare_proxy_css_server_timeout: "2h"
censhare_proxy_css_client_timeout: "2h"
censhare_proxy_cgw_server_timeout: "1h"
censhare_proxy_cgw_client_timeout: "1h"

censhare_proxy_default_redirect: "censhare5/client"

censhare_proxy_ssl: "self-signed"
censhare_proxy_ssl_domain: "www.example.com"
censhare_proxy_domain_pem: ""
censhare_proxy_ssl_acme_fingerprint: ""

censhare_proxy_stats_enabled: false
censhare_proxy_stats_port: 8404
censhare_proxy_stats_uri: /stats
censhare_proxy_stats_refresh: 10s
censhare_proxy_stats_user: admin
censhare_proxy_stats_pass: admin

# censhare_proxy_redirect_kc_idp_hint:
#   - name: foobar
#     method: uri
#     uri: "/foobar"
#   - name: barfoo
#     method: param
